### ISSUE TITLE
Adding an IP address makes the adapter find two Things

### ISSUE THREAD

**Issue by madb1lly** [tim-hellhake/tasmota-adapter#35]
Hi @tim-hellhake,

If I add the IP address of the Tasmota device then the adapter finds two Things in the Gateway's add thing UI:

1. The device with the Tasmota ID and all the on/off and temp, humidity or dew point properties
2. A device with the IP address as the ID and only showing the on/off properties, not the temp, humidity or dew point properties.

The two devices act independently as you would expect, i.e. if I trigger an on/off property on one Thing the gateway updates the Tasmota device and then the other Thing then reads the new state and is updated. Here are the internal log entries relevant to turning the Tasmota device on from the main Things page (remember this device has two outputs) and how the two Things then react when they get the status readback:
```
2020-09-04 14:38:19.016 INFO   : tasmota-adapter: Set value of tasmota_C83947-6471 / Fan On / Off to true []
2020-09-04 14:38:19.018 INFO   : tasmota-adapter: setCachedValueAndNotify for property on1 from false to true for tasmota_C83947-6471.local
2020-09-04 14:38:19.020 INFO   : tasmota-adapter: Set value of tasmota_C83947-6471 / Speed Low / High to true []
2020-09-04 14:38:19.022 INFO   : tasmota-adapter: setCachedValueAndNotify for property on2 from false to true for tasmota_C83947-6471.local
2020-09-04 14:38:19.024 INFO   : tasmota-adapter: setCachedValueAndNotify for property on from false to true for tasmota_C83947-6471.local
2020-09-04 14:38:19.402 INFO   : tasmota-adapter: Executed setStatus in 411 ms []
2020-09-04 14:38:19.408 INFO   : tasmota-adapter:  []
2020-09-04 14:38:19.466 INFO   : tasmota-adapter: Executed setStatus in 462 ms []
2020-09-04 14:38:19.470 INFO   : tasmota-adapter:  []
2020-09-04 14:38:25.381 INFO   : tasmota-adapter: Executed getStatus in 49 ms []
2020-09-04 14:38:25.383 INFO   : tasmota-adapter: setCachedValueAndNotify for property on1 from false to true for 192.168.1.44
2020-09-04 14:38:25.387 INFO   : tasmota-adapter: setCachedValueAndNotify for property on from false to true for 192.168.1.44
2020-09-04 14:38:25.391 INFO   : tasmota-adapter: Value of 192.168.1.44 / Fan On / Off changed to true []
2020-09-04 14:38:25.436 INFO   : tasmota-adapter: Executed getStatus in 97 ms []
2020-09-04 14:38:25.441 INFO   : tasmota-adapter: setCachedValueAndNotify for property on2 from false to true for 192.168.1.44
2020-09-04 14:38:25.444 INFO   : tasmota-adapter: Value of 192.168.1.44 / Speed Low / High changed to true []
2020-09-04 14:38:25.493 INFO   : tasmota-adapter: Executed getStatus in 151 ms []
2020-09-04 14:38:25.550 INFO   : tasmota-adapter: Executed getStatus in 200 ms []
2020-09-04 14:38:25.553 INFO   : tasmota-adapter: Value of tasmota_C83947-6471 / Fan On / Off changed to true []
2020-09-04 14:38:25.601 INFO   : tasmota-adapter: Executed getStatus in 250 ms []
2020-09-04 14:38:25.604 INFO   : tasmota-adapter: Value of tasmota_C83947-6471 / Speed Low / High changed to true []
```
So the odd thing is that the adapter finds two Things but doesn't populate them with the same properties.

Cheers 🙂

**Comment by tim-hellhake** [comment]
I guess the one you added manually was also discovered.
I'll add a filter for already known devices.

> but doesn't populate them with the same properties

Ok, that's strange...

Which one is correct?

**Comment by tim-hellhake** [comment]
The issue should be resolved with the latest update.
Do you still have duplicated things?

**Comment by madb1lly** [comment]
Hi @tim-hellhake,

Thanks for the update. I removed both things and removed the IP address from the add-on config. I then searched for a new Thing and found the tasmota and added it. I then added the IP address to the add-on config and did another search for a new Thing and it found the Thing with the IP address, same as before.

So unfortunately I don't think it's fixed. Or have I misunderstood what the fix looks like?

Cheers 🙂

**Comment by tim-hellhake** [comment]
>  Or have I misunderstood what the fix looks like?

No, it should be fixed with the latest version.
Can you please enable debug logs, restart the adapter and attach the logs to the issue?

**Comment by madb1lly** [comment]
Hello @tim-hellhake,

Here's the adapter configuration:
![image](https://user-images.githubusercontent.com/25123631/93876434-25c42080-fcd7-11ea-89e0-7cf0839657a2.png)
On the Add Things page I have these entries:
![image](https://user-images.githubusercontent.com/25123631/93876521-48563980-fcd7-11ea-9639-3ca5fdedff60.png)
and
![image](https://user-images.githubusercontent.com/25123631/93876539-4e4c1a80-fcd7-11ea-8cd7-bcab163d70ab.png)
I add only the device recognised as Tasmota and I don't add the one by IP address. I rebooted to make sure there is nothing cached and oddly the Tasmota device I had added before is now shown as disconnected. In the Add Thing UI I can still see the device by IP address. 

I then remove the IP address from the Tasmota adapter config and now the first Tasmota device is connected again. I reboot and afterwards the one added by IP address is now disconnected.
![image](https://user-images.githubusercontent.com/25123631/93878098-d0d5d980-fcd9-11ea-8b71-aba9204abeea.png)
There's a lot in the logs, which particular bits would you like to see?

Cheers 🙂

**Comment by tim-hellhake** [comment]
> There's a lot in the logs, which particular bits would you like to see?

I would expect something like `Ignoring ... because ...`
Unfortunately, the IP of the discovered device is not logged, so I think I need to prepare a new update for this.

**Comment by madb1lly** [comment]
Hi @tim-hellhake,

So I should test again with the new update? Same steps I used as before or would you like to do something different this time?

Cheers 🙂

**Comment by tim-hellhake** [comment]
I added some new logs.
It would ne helpful if you could upload the logs after restarting the adapter.
You don't need to remove and add the devices again.

**Comment by madb1lly** [comment]
Hi @tim-hellhake,

I disabled and reenabled, here are the logs after restart:

```
2020-09-28 15:36:04.548 INFO   : tasmota-adapter: Loading add-on tasmota-adapter from /home/pi/.mozilla-iot/addons/tasmota-adapter
2020-09-28 15:36:05.009 ERROR  : Invalid message received: { messageType: 4096,
  data:
   { adapterId: 'Tasmota',
     name: 'TasmotaAdapter',
     pluginId: 'tasmota-adapter' } }
2020-09-28 15:36:05.064 INFO   : tasmota-adapter: Loading devices from config []
2020-09-28 15:36:05.067 INFO   : tasmota-adapter: Starting discovery []
2020-09-28 15:36:05.150 INFO   : tasmota-adapter: Ignoring []
2020-09-28 15:36:05.565 INFO   : tasmota-adapter: Discovered http service at tasmota_C83947-6471.local (["192.168.1.44"]]) []
2020-09-28 15:36:05.569 INFO   : tasmota-adapter: Probing 192.168.1.44:80 []
2020-09-28 15:36:05.882 INFO   : tasmota-adapter: Discovered Tasmota at tasmota_C83947-6471.local []
2020-09-28 15:36:05.886 INFO   : tasmota-adapter: Creating device tasmota_C83947-6471.local (192.168.1.44) []
2020-09-28 15:36:06.166 INFO   : tasmota-adapter: Detected channel 1 (Fan On / Off) []
2020-09-28 15:36:07.203 INFO   : tasmota-adapter: Detected channel 2 (Speed Low / High) []
2020-09-28 15:36:07.244 INFO   : tasmota-adapter: Channel 3 not available []
2020-09-28 15:36:07.298 INFO   : tasmota-adapter: Channel 4 not available []
2020-09-28 15:36:07.350 INFO   : tasmota-adapter: Channel 5 not available []
2020-09-28 15:36:07.401 INFO   : tasmota-adapter: Channel 6 not available []
2020-09-28 15:36:07.453 INFO   : tasmota-adapter: Channel 7 not available []
2020-09-28 15:36:07.507 INFO   : tasmota-adapter: Channel 8 not available []
2020-09-28 15:36:07.565 INFO   : tasmota-adapter: Channel 9 not available []
2020-09-28 15:36:07.570 INFO   : tasmota-adapter: Found channels [{"id":"1","friendlyName":"Fan On / Off"},{"id":"2","friendlyName":"Speed Low / High"}] []
2020-09-28 15:36:07.641 INFO   : tasmota-adapter: Creating property for channel on1 (Fan On / Off) []
2020-09-28 15:36:07.645 INFO   : tasmota-adapter: Creating property for channel on2 (Speed Low / High) []
2020-09-28 15:36:07.647 INFO   : tasmota-adapter: Parsed data: {"SI7021 Temperature":{"value":24.6,"symbol":"°C"},"SI7021 Humidity":{"value":49.5,"symbol":"%"},"SI7021 Dew point":{"value":13.3,"symbol":"°C"}} []
2020-09-28 15:36:07.652 INFO   : tasmota-adapter: setCachedValueAndNotify for property temperature from undefined to 24.6 for tasmota_C83947-6471.local
2020-09-28 15:36:07.658 INFO   : tasmota-adapter: setCachedValueAndNotify for property humidity from undefined to 49.5 for tasmota_C83947-6471.local
2020-09-28 15:36:07.665 INFO   : tasmota-adapter: setCachedValueAndNotify for property dewPoint from undefined to 13.3 for tasmota_C83947-6471.local
2020-09-28 15:36:08.550 INFO   : getValue for property temperature for: tasmota_C83947-6471 returning 24.6
2020-09-28 15:36:08.552 INFO   : getValue for property humidity for: tasmota_C83947-6471 returning 49.5
2020-09-28 15:36:08.555 INFO   : getValue for property dewPoint for: tasmota_C83947-6471 returning 13.3
2020-09-28 15:36:17.938 INFO   : tasmota-adapter: Executed getStatus in 242 ms []
2020-09-28 15:36:17.951 INFO   : tasmota-adapter: setCachedValueAndNotify for property on1 from undefined to false for tasmota_C83947-6471.local
2020-09-28 15:36:17.955 INFO   : tasmota-adapter: setCachedValueAndNotify for property on from undefined to false for tasmota_C83947-6471.local
2020-09-28 15:36:17.958 INFO   : tasmota-adapter: Value of tasmota_C83947-6471 / Fan On / Off changed to false []
2020-09-28 15:36:17.988 INFO   : tasmota-adapter: Executed getStatus in 290 ms []
2020-09-28 15:36:18.002 INFO   : tasmota-adapter: setCachedValueAndNotify for property on2 from undefined to false for tasmota_C83947-6471.local
2020-09-28 15:36:18.005 INFO   : tasmota-adapter: Value of tasmota_C83947-6471 / Speed Low / High changed to false []
2020-09-28 15:36:18.041 INFO   : tasmota-adapter: Executed getStatus in 339 ms []
2020-09-28 15:36:18.047 INFO   : tasmota-adapter: setCachedValueAndNotify for property temperature from 24.6 to 24.7 for tasmota_C83947-6471.local
2020-09-28 15:36:18.059 INFO   : tasmota-adapter: setCachedValueAndNotify for property humidity from 49.5 to 49.6 for tasmota_C83947-6471.local
2020-09-28 15:36:18.062 INFO   : tasmota-adapter: setCachedValueAndNotify for property dewPoint from 13.3 to 13.4 for tasmota_C83947-6471.local
2020-09-28 15:36:18.680 INFO   : getValue for property on2 for: tasmota_C83947-6471 returning false
2020-09-28 15:36:18.744 INFO   : getValue for property on1 for: tasmota_C83947-6471 returning false
```

I haven't made any changes to anything else, so I still have 192.168.1.44 added manually in the add-on ocnfig and the disconnected 192.168.1.44 thing on the main page is still there. The Tasmota thing is connected and working correctly as far as I can tell.

Cheers 🙂

**Comment by tim-hellhake** [comment]
According to the log, there are no manually configured devices.
Otherwise, there would be a log message like ` Creating device 192.168.1.44 (192.168.1.44)`.
That would also explain why the device is shown as disconnected.

Can you please
* delete the disconnected device in the gateway
* add `192.168.1.44` to the adapter config
* restart the adapter
* add the adapter logs to the issue

The current procedure after an adapter restart is:
* add all manually configured devices
* start the discovery
* ignore all found devices which are already added by ip

That should prevent duplicates.

**Comment by madb1lly** [comment]
Hi @tim-hellhake,
I followed the steps and here are the logs:
```
2020-09-29 14:23:27.946 INFO   : tasmota-adapter: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2020-09-29 14:23:29.926 INFO   : tasmota-adapter: Loading add-on tasmota-adapter from /home/pi/.mozilla-iot/addons/tasmota-adapter
2020-09-29 14:23:30.423 ERROR  : Invalid message received: { messageType: 4096,
  data:
   { adapterId: 'Tasmota',
     name: 'TasmotaAdapter',
     pluginId: 'tasmota-adapter' } }
2020-09-29 14:23:30.473 INFO   : tasmota-adapter: Loading devices from config []
2020-09-29 14:23:30.477 INFO   : tasmota-adapter: Starting discovery []
2020-09-29 14:23:30.542 INFO   : tasmota-adapter: Ignoring ["192.168.1.44"]
2020-09-29 14:23:30.643 INFO   : tasmota-adapter: Creating device 192.168.1.44 (192.168.1.44) []
2020-09-29 14:23:31.022 INFO   : tasmota-adapter: Discovered http service at tasmota_C83947-6471.local (["192.168.1.44"]]) []
2020-09-29 14:23:31.027 INFO   : tasmota-adapter: Ignoring tasmota_C83947-6471.local because 192.168.1.44 was already configured manually []
2020-09-29 14:23:31.154 ERROR  : tasmota-adapter: Could not get data: FetchError: request to http://192.168.1.44:0/?m=1 failed, reason: connect ECONNREFUSED 192.168.1.44
2020-09-29 14:23:31.337 INFO   : tasmota-adapter: Detected channel 1 (Fan On / Off) []
2020-09-29 14:23:31.381 INFO   : tasmota-adapter: Detected channel 2 (Speed Low / High) []
2020-09-29 14:23:31.426 INFO   : tasmota-adapter: Channel 3 not available []
2020-09-29 14:23:31.484 INFO   : tasmota-adapter: Channel 4 not available []
2020-09-29 14:23:32.509 INFO   : tasmota-adapter: Channel 5 not available []
2020-09-29 14:23:32.563 INFO   : tasmota-adapter: Channel 6 not available []
2020-09-29 14:23:32.630 INFO   : tasmota-adapter: Channel 7 not available []
2020-09-29 14:23:32.679 INFO   : tasmota-adapter: Channel 8 not available []
2020-09-29 14:23:32.727 INFO   : tasmota-adapter: Channel 9 not available []
2020-09-29 14:23:32.732 INFO   : tasmota-adapter: Found channels [{"id":"1","friendlyName":"Fan On / Off"},{"id":"2","friendlyName":"Speed Low / High"}] []
2020-09-29 14:23:32.788 INFO   : tasmota-adapter: Creating property for channel on1 (Fan On / Off) []
2020-09-29 14:23:32.793 INFO   : tasmota-adapter: Creating property for channel on2 (Speed Low / High) []
2020-09-29 14:23:32.797 INFO   : tasmota-adapter: Parsed data: {} [] 
```
The automatically detected device still shows as connected but no longer responds to actions. In the add new thing UI I can see 192.168.1.44 again.

After reboot the automatically detected device is now shown disconnected and 192.168.1.44 is available in the add new thing UI.

So is that all working as intended?

Note that in all cases the 192.168.1.44 thing only shows the on/off characteristics, not the temperature, pressure or dew point which the automatically detected thing shows.

For my purposes, I think I can just remove the 192.168.1.44 thing from the add-on config, because I don't need it, I can just use the automatically detected thing.

Cheers 🙂

**Comment by tim-hellhake** [comment]
> So is that all working as intended?

Yeah, that's the expected behavior.
Automatically detected devices use their hostname as `id` while manually added devices use a generated `id` to allow you to reconfigure the IP address without creating a new device.
That's the reason why there are two devices.
You need to delete one of them.
If you want to use the automatically detected one you need to remove the IP from the adapter config.

> Note that in all cases the 192.168.1.44 thing only shows the on/off characteristics, not the temperature, pressure or dew point which the automatically detected thing shows.

According to the log, it tries to connect to port `0`.
I guess the port in config is also `0`.
This breaks the device detection.
I'll add a default in the code to prevent this.

**Comment by madb1lly** [comment]
Hi @tim-hellhake,

Thanks for confirming.

On version 2.0.2 it says default port is 80 so I assumed if I left it as 0 (which it was, by default) then it would ignore 0 and use 80. When my add-on updates to 2.0.3 I'll test again and see if it picks up the sensor measurements this time.

Cheers 🙂

PS - I tried port 80 and it works, everything is identified.

**Comment by tim-hellhake** [comment]
Nice!
Can we close the issue or is something missing?

**Comment by madb1lly** [comment]
Hi @tim-hellhake,
I just tested on the latest version and port=0 defaults to port=80 and then detects all the properties fine 😃
So yes we can close it now!
Cheers 🙂
